CREATE DATABASE IF NOT EXISTS onobill; USE onobill;
CREATE TABLE tenants (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), created_at BIGINT);
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(255), password_hash VARCHAR(255), role VARCHAR(50), tenant_id INT);